### ISSUE TITLE
🎁 Add Handler Method for Word Coordinates, Text, and Alto XML

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/space_stone-serverless#19]
Depending on the approach in the below mentioned dependencies, we will either run one generator in SpaceStone or we will run the three generators consecutively in SpaceStone.

Depends on:

- scientist-softserv/derivative_rodeo#27
- scientist-softserv/derivative_rodeo#28
- https://github.com/scientist-softserv/derivative_rodeo/issues/6

**Comment by ShanaLMoore** [comment]
Assigning to @kirkkwang because I believe started this work in our swarm session yesterday.
